import {
  // BadgeDollarSign,
  SquareKanban,
  // Calendar,
  // User,
  LayoutDashboard,
  FileSpreadsheet,
  RotateCcw,
  // Laptop,
  // Printer,
  // TestTube,
  PaintBucket,
  Users,
} from "lucide-react";
import type { OfficeNavigationItem } from "./officeNavigation.types";

export const backOfficeNavigation: OfficeNavigationItem[] = [
  {
    id: "dashboard",
    path: "/admin",
    label: "Dashboard",
    description: "Vue analytique et configuration avancée",
    Icon: LayoutDashboard,
  },
  {
    id: "tickets",
    path: "/admin/tickets",
    label: "Tickets",
    description: "Synthèse globale et activité récente",
    Icon: SquareKanban,
  },
    {
    id: "kanban-settings",
    path: "/admin/kanban-settings",
    label: "Kanban settings",
    description: "Couleurs et labels malgaches du kanban",
    Icon: PaintBucket,
  },
  {
    id: "import-data",
    path: "/admin/import-data",
    label: "Import data",
    description: "Import CSV multi-ressources GLPI",
    Icon: FileSpreadsheet,
  },
  {
    id: "reset-data",
    path: "/admin/reset-data",
    label: "Reset data",
    description: "Réinitialisation multi-ressources GLPI",
    Icon: RotateCcw,
    // isHorizontalRowDown: true,
  },
  {
    id: "user-test",
    path: "/admin/user-test",
    label: "User Test",
    description: "CRUD local user test via SQLite",
    Icon: Users,
  },

  // {
  //   id: "dashboard-other",
  //   path: "/admin/dashboard-other",
  //   label: "Administration TEST",
  //   description: "Vue analytique et configuration avancée (Page de test)",
  //   Icon: LayoutDashboard,
  // },
  // {
  //   id: "parcs",
  //   path: "/admin/parcs",
  //   label: "Parc",
  //   description: "Ordinateurs, matériels et inventaire",
  //   Icon: BadgeDollarSign,
  // },
  // {
  //   id: "knowledge-base",
  //   path: "/admin/knowledge-base",
  //   label: "Base de connaissances",
  //   description: "Organisation, process et documentation",
  //   Icon: Calendar,
  // },
  // {
  //   id: "assets",
  //   path: "/admin/assets",
  //   label: "Assets",
  //   description: "Listes des Assets de GLPI",
  //   Icon: SquareKanban,
  // },
  // {
  //   id: "users",
  //   path: "/admin/users",
  //   label: "Utilisateurs",
  //   description: "Gestion des utilisateurs GLPI",
  //   Icon: User,
  // },
  // {
  //   id: "computers",
  //   path: "/admin/computers",
  //   label: "Computer",
  //   description: "Données détailler sur le computer",
  //   Icon: Laptop,
  // },
  // {
  //   id: "printers",
  //   path: "/admin/printers",
  //   label: "Printer",
  //   description: "Données détailler sur le printer",
  //   Icon: Printer,
  // },
  // {
  //   id: "memo-test",
  //   path: "/admin/memo-test",
  //   label: "memo-test",
  //   description: "memo-test",
  //   Icon: TestTube,
  // },
];
